language: cpp
dist: xenial
before_script:
- sudo apt-add-repository -y "deb http://archive.ubuntu.com/ubuntu xenial main universe"
- sudo apt-get install -y libgtest-dev build-essential cmake
- pushd /usr/src/gtest
- sudo cmake .
- sudo cmake --build . -- -j "`nproc`"
- sudo cp *.a /usr/lib
- popd
script:
- cmake -D BUILD_TYPE_RELEASE=ON .
- cmake --build . -- -j "`nproc`"
- cmake --build . --target test -- -j "`nproc`"
- cmake --build . --target package -- -j "`nproc`"
deploy:
  provider: script
  skip_cleanup: true
  debug: on
  script:
    - curl -T "ipfilter-prog_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb" -u sergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/03-2019.01.10/ipfilter/0.0.${TRAVIS_BUILD_NUMBER}/pool/main/i/ipfilter/ipfilter-prog_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1" -T "ipfilter-lib_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb" -u sergmusor:"$BINTRAY_API_KEY" "https://api.bintray.com/content/sergmusor/03-2019.01.10/ipfilter/0.0.${TRAVIS_BUILD_NUMBER}/pool/main/i/ipfilter/ipfilter-lib_0.0.${TRAVIS_BUILD_NUMBER}_amd64.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
deploy:
  provider: pages
  local-dir: docs
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  on:
    branch: master
