language: cpp
dist: xenial
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - libgtest-dev
      - build-essential
      - cmake
      - doxygen
      - graphviz
before_script:
- apt-get purge g++-5
- apt-get autoremove
- pushd /usr/src/gtest
- sudo cmake .
- sudo cmake --build . -- -j "`nproc`"
- sudo cp *.a /usr/lib
- popd
script:
- cmake -D BUILD_TYPE_RELEASE=ON .
- cmake --build . -- -j "`nproc`"
- cmake --build . --target test -- -j "`nproc`"
- cmake --build . --target package -- -j "`nproc`"
- doxygen
deploy:
  - provider: script
    skip_cleanup: true
    debug: on
    script: bash .deploy.sh "$TRAVIS_BUILD_NUMBER" "$BINTRAY_API_KEY"
    on:
      branch: master
  - provider: pages
    local-dir: html
    skip_cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep_history: false
    verbose: true
    on:
      branch: master
